package components.entity;
// Generated Mar 16, 2018 2:40:42 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private long accountId;
     private String usename;
     private String password;
     private Serializable firstName;
     private Serializable lastName;
     private String numPhone;
     private String email;
     private boolean inActive;
     private int role;
     private Set<DeliveryBill> deliveryBills = new HashSet<DeliveryBill>(0);
     private Set<Receipt> receipts = new HashSet<Receipt>(0);
     private Set<DeliveryBill> deliveryBills_1 = new HashSet<DeliveryBill>(0);

    public Account() {
    }

	
    public Account(long accountId, String usename, String password, boolean inActive, int role) {
        this.accountId = accountId;
        this.usename = usename;
        this.password = password;
        this.inActive = inActive;
        this.role = role;
    }
    public Account(long accountId, String usename, String password, Serializable firstName, Serializable lastName, String numPhone, String email, boolean inActive, int role, Set<DeliveryBill> deliveryBills, Set<Receipt> receipts, Set<DeliveryBill> deliveryBills_1) {
       this.accountId = accountId;
       this.usename = usename;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.numPhone = numPhone;
       this.email = email;
       this.inActive = inActive;
       this.role = role;
       this.deliveryBills = deliveryBills;
       this.receipts = receipts;
       this.deliveryBills_1 = deliveryBills_1;
    }
   
    public long getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(long accountId) {
        this.accountId = accountId;
    }
    public String getUsename() {
        return this.usename;
    }
    
    public void setUsename(String usename) {
        this.usename = usename;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Serializable getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(Serializable firstName) {
        this.firstName = firstName;
    }
    public Serializable getLastName() {
        return this.lastName;
    }
    
    public void setLastName(Serializable lastName) {
        this.lastName = lastName;
    }
    public String getNumPhone() {
        return this.numPhone;
    }
    
    public void setNumPhone(String numPhone) {
        this.numPhone = numPhone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isInActive() {
        return this.inActive;
    }
    
    public void setInActive(boolean inActive) {
        this.inActive = inActive;
    }
    public int getRole() {
        return this.role;
    }
    
    public void setRole(int role) {
        this.role = role;
    }
    public Set<DeliveryBill> getDeliveryBills() {
        return this.deliveryBills;
    }
    
    public void setDeliveryBills(Set<DeliveryBill> deliveryBills) {
        this.deliveryBills = deliveryBills;
    }
    public Set<Receipt> getReceipts() {
        return this.receipts;
    }
    
    public void setReceipts(Set<Receipt> receipts) {
        this.receipts = receipts;
    }
    public Set<DeliveryBill> getDeliveryBills_1() {
        return this.deliveryBills_1;
    }
    
    public void setDeliveryBills_1(Set<DeliveryBill> deliveryBills_1) {
        this.deliveryBills_1 = deliveryBills_1;
    }




}


