package components.entity;
// Generated Mar 16, 2018 2:40:42 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private long categoryId;
     private String name;
     private Set products = new HashSet(0);

    public Category() {
    }

	
    public Category(long categoryId, String name) {
        this.categoryId = categoryId;
        this.name = name;
    }
    public Category(long categoryId, String name, Set products) {
       this.categoryId = categoryId;
       this.name = name;
       this.products = products;
    }
   
    public long getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


