package components.entity;
// Generated Mar 10, 2018 10:38:29 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DeliveryBill generated by hbm2java
 */
public class DeliveryBill  implements java.io.Serializable {


     private long deliveryBillId;
     private Account account;
     private Partner partner;
     private Date datetime;

    public DeliveryBill() {
    }

    public DeliveryBill(long deliveryBillId, Account account, Partner partner, Date datetime) {
       this.deliveryBillId = deliveryBillId;
       this.account = account;
       this.partner = partner;
       this.datetime = datetime;
    }
   
    public long getDeliveryBillId() {
        return this.deliveryBillId;
    }
    
    public void setDeliveryBillId(long deliveryBillId) {
        this.deliveryBillId = deliveryBillId;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Partner getPartner() {
        return this.partner;
    }
    
    public void setPartner(Partner partner) {
        this.partner = partner;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }




}


