package components.entity;
// Generated Mar 10, 2018 10:38:29 AM by Hibernate Tools 4.3.1



/**
 * DeliveryBillDetail generated by hbm2java
 */
public class DeliveryBillDetail  implements java.io.Serializable {


     private long deliveryBillDetailId;
     private Product product;
     private long deliveryBillId;
     private int quantity;

    public DeliveryBillDetail() {
    }

    public DeliveryBillDetail(long deliveryBillDetailId, Product product, long deliveryBillId, int quantity) {
       this.deliveryBillDetailId = deliveryBillDetailId;
       this.product = product;
       this.deliveryBillId = deliveryBillId;
       this.quantity = quantity;
    }
   
    public long getDeliveryBillDetailId() {
        return this.deliveryBillDetailId;
    }
    
    public void setDeliveryBillDetailId(long deliveryBillDetailId) {
        this.deliveryBillDetailId = deliveryBillDetailId;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public long getDeliveryBillId() {
        return this.deliveryBillId;
    }
    
    public void setDeliveryBillId(long deliveryBillId) {
        this.deliveryBillId = deliveryBillId;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


