package components.entity;
// Generated Mar 16, 2018 2:40:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DeliveryBill generated by hbm2java
 */
public class DeliveryBill  implements java.io.Serializable {


     private long deliveryBillId;
     private Account account;
     private Partner partner;
     private Date datetime;
     private int status;
     private Set deliveryBillDetails = new HashSet(0);

    public DeliveryBill() {
    }

	
    public DeliveryBill(long deliveryBillId, Date datetime, int status) {
        this.deliveryBillId = deliveryBillId;
        this.datetime = datetime;
        this.status = status;
    }
    public DeliveryBill(long deliveryBillId, Account account, Partner partner, Date datetime, int status, Set deliveryBillDetails) {
       this.deliveryBillId = deliveryBillId;
       this.account = account;
       this.partner = partner;
       this.datetime = datetime;
       this.status = status;
       this.deliveryBillDetails = deliveryBillDetails;
    }
   
    public long getDeliveryBillId() {
        return this.deliveryBillId;
    }
    
    public void setDeliveryBillId(long deliveryBillId) {
        this.deliveryBillId = deliveryBillId;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Partner getPartner() {
        return this.partner;
    }
    
    public void setPartner(Partner partner) {
        this.partner = partner;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Set getDeliveryBillDetails() {
        return this.deliveryBillDetails;
    }
    
    public void setDeliveryBillDetails(Set deliveryBillDetails) {
        this.deliveryBillDetails = deliveryBillDetails;
    }




}


