package components.entity;
// Generated Mar 16, 2018 1:48:13 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Receipt generated by hbm2java
 */
public class Receipt  implements java.io.Serializable {


     private long receiptId;
     private Account account;
     private Partner partner;
     private Date datetime;
     private int status;
     private Set<ReceiptDetail> receiptDetails = new HashSet<ReceiptDetail>(0);

    public Receipt() {
    }

	
    public Receipt(long receiptId, Date datetime, int status) {
        this.receiptId = receiptId;
        this.datetime = datetime;
        this.status = status;
    }
    public Receipt(long receiptId, Account account, Partner partner, Date datetime, int status, Set<ReceiptDetail> receiptDetails) {
       this.receiptId = receiptId;
       this.account = account;
       this.partner = partner;
       this.datetime = datetime;
       this.status = status;
       this.receiptDetails = receiptDetails;
    }
   
    public long getReceiptId() {
        return this.receiptId;
    }
    
    public void setReceiptId(long receiptId) {
        this.receiptId = receiptId;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Partner getPartner() {
        return this.partner;
    }
    
    public void setPartner(Partner partner) {
        this.partner = partner;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Set<ReceiptDetail> getReceiptDetails() {
        return this.receiptDetails;
    }
    
    public void setReceiptDetails(Set<ReceiptDetail> receiptDetails) {
        this.receiptDetails = receiptDetails;
    }




}


