package components.entity;
// Generated Mar 16, 2018 2:40:42 PM by Hibernate Tools 4.3.1



/**
 * ReceiptDetail generated by hbm2java
 */
public class ReceiptDetail  implements java.io.Serializable {


     private long receiptDetailId;
     private Product product;
     private Receipt receipt;
     private int quantity;

    public ReceiptDetail() {
    }

	
    public ReceiptDetail(long receiptDetailId, int quantity) {
        this.receiptDetailId = receiptDetailId;
        this.quantity = quantity;
    }
    public ReceiptDetail(long receiptDetailId, Product product, Receipt receipt, int quantity) {
       this.receiptDetailId = receiptDetailId;
       this.product = product;
       this.receipt = receipt;
       this.quantity = quantity;
    }
   
    public long getReceiptDetailId() {
        return this.receiptDetailId;
    }
    
    public void setReceiptDetailId(long receiptDetailId) {
        this.receiptDetailId = receiptDetailId;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Receipt getReceipt() {
        return this.receipt;
    }
    
    public void setReceipt(Receipt receipt) {
        this.receipt = receipt;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


