/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components.interfaces;

import components.applications.application;
import components.entity.Account;
import static components.interfaces.frmLogin.accountId;
import components.services.AccountService;
import components.utils.MD5Library;
import components.utils.StringHelpers;
import java.util.ArrayList;

/**
 *
 * @author MitsuyoRai
 */
public class frmChangePass extends javax.swing.JPanel {
    protected AccountService accountService;
    /**
     * Creates new form frmChangePass
     */
    public frmChangePass() {
        initComponents();
        accountService = new AccountService();
        lblUsername.setText(application.user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtOldPass = new javax.swing.JPasswordField();
        txtReNewPass = new javax.swing.JPasswordField();
        btnChangePass = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNewPass = new javax.swing.JPasswordField();

        jLabel1.setText("ĐỔI MẬT KHẨU");

        jLabel2.setText("Username:");

        jLabel3.setText("Mật khẩu cũ:");

        jLabel4.setText("Nhập lại mật khẩu mới:");

        lblUsername.setText("....................");

        btnChangePass.setText("Đổi mật khẩu");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        jLabel5.setText("Mật khẩu mới:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnChangePass)
                                    .addComponent(lblUsername)
                                    .addComponent(txtOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtReNewPass)
                                    .addComponent(txtNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblUsername))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtReNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(btnChangePass)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        // TODO add your handling code here:
        //String strUsername = txtUserName2.getText().trim();
        String oldPass = new String(txtOldPass.getPassword());
        String newPass = new String(txtNewPass.getPassword());
        String renewPass = new String(txtReNewPass.getPassword());
        
        if (oldPass.equals("")) {
            StringHelpers.Message("Vui lòng nhập mật khẩu cũ", "Thông báo", 2);
            txtOldPass.requestFocus();
            return;
        } else if(!accountService.hasUsernamePassword(application.user, MD5Library.md5(oldPass))){
            StringHelpers.Message("Mật khẩu cũ không đúng", "Thông báo", 2);
            txtOldPass.requestFocus();
            return;
        } else if (newPass.equals("")) {
            StringHelpers.Message("Vui lòng nhập mật khẩu mới", "Thông báo", 2);
            txtReNewPass.requestFocus();
            return;
        } else if( newPass.equals(renewPass) == false ){
            StringHelpers.Message("Nhập lại mật khẩu không đúng", "Thông báo", 2);
            txtReNewPass.requestFocus();
            return;
        } 
        try {
            ArrayList rs = accountService.getLogin(application.user, MD5Library.md5(oldPass));
            if( rs != null ) { 
                String firstname = rs.get(2).toString(); 
                String lastname = rs.get(3).toString(); 
                String email = rs.get(6).toString(); 
                String numphone = rs.get(5).toString();
                
                Account dto = new Account();
                dto.setAccountId(application.accountId);
                dto.setUsername(application.user);
                dto.setPassword(MD5Library.md5(newPass));
                dto.setFirstName(firstname);
                dto.setLastName(lastname);
                dto.setNumPhone(numphone);
                dto.setEmail(email);
                dto.setInActive(true);
                dto.setRole(application.role);
                
                if( accountService.update(dto) ){
                    StringHelpers.Message("Đổi mật khẩu thành công", "Thành công", 1);
                    txtOldPass.setText("");
                    txtNewPass.setText("");
                    txtReNewPass.setText("");
                } else {
                    StringHelpers.Message("Lỗi xử lý, vui lòng thử lại.", "Error", 2);
                }
            }
         } catch(Exception e) {
             StringHelpers.Message("Lỗi xử lý, vui lòng thử lại 2.", "Error", 2);
             StringHelpers.Message("Lỗi xử lý, vui lòng thử lại.", "Error", 2);
         }
    }//GEN-LAST:event_btnChangePassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtNewPass;
    private javax.swing.JPasswordField txtOldPass;
    private javax.swing.JPasswordField txtReNewPass;
    // End of variables declaration//GEN-END:variables
}
