/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components.interfaces;

import components.entity.Partner;
import components.services.PartnerService;
import components.utils.StringHelpers;
import java.io.Serializable;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MitsuyoRai
 */
public class frmPartner extends javax.swing.JPanel {
    private int _partnerId = -1;
    PartnerService partnerService;
    /**
     * Creates new form frmPartner
     */
    public frmPartner() {
        initComponents();
        partnerService = new PartnerService();
    }
    
    //--Code Đồi tác---------------------------------------------------=-/
    private void getDataPartner() {
        Object[] obj = new Object[]{"ID", "STT", "Tên đối tác", "Mô tả", "Địa chỉ", "Số điện thoại", "Tên người đại diện"};
        DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
        jTablePartner.setModel(tableModel);
        int c = 0;
        try {
            List<Partner> listPartner = partnerService.getDataPartner();
            if( listPartner != null ) {
                for( int i =0; i < listPartner.size(); i++ ){
                    Object[] item = new Object[7];
                    item[0] = listPartner.get(i).getPartnerId();
                    item[1] = ++c;
                    item[2] = listPartner.get(i).getPartnerName();
                    item[3] = listPartner.get(i).getDescription();
                    item[4] = listPartner.get(i).getAddress();
                    item[5] = listPartner.get(i).getNumPhone();
                    item[6] = listPartner.get(i).getRepresentFullname();
                    tableModel.addRow(item);
                }           
            }  
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }
    
    private void resetTablePartner()
    {
        txtTenDoiTac.setText("");
        txtTenNDD.setText("");
        txtSoDienThoai.setText("");
        txtDiaChi.setText("");
        jTextAreaMoTa.setText("");
        
    }
    //---------------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDanhSachDoiTac = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePartner = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTenDoiTac = new javax.swing.JTextField();
        txtTenNDD = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtDiaChi = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaMoTa = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jTablePartner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "STT", "Tên đối tác", "Mô tả", "Địa chỉ", "Số điện thoại", "Tên người đại diện"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTablePartner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePartnerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePartner);

        jLabel8.setText("Tên đối tác:");

        jLabel9.setText("Tên Người đại diện:");

        jLabel10.setText("Số điện thoại:");

        jLabel11.setText("Địa chỉ:");

        jLabel12.setText("Mô tả:");

        btnInsert.setText("Thêm");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setText("Chỉnh sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTextAreaMoTa.setColumns(20);
        jTextAreaMoTa.setRows(5);
        jScrollPane3.setViewportView(jTextAreaMoTa);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenDoiTac, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(txtTenNDD, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTenDoiTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTenNDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel12)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Tìm kiếm");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelDanhSachDoiTacLayout = new javax.swing.GroupLayout(jPanelDanhSachDoiTac);
        jPanelDanhSachDoiTac.setLayout(jPanelDanhSachDoiTacLayout);
        jPanelDanhSachDoiTacLayout.setHorizontalGroup(
            jPanelDanhSachDoiTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDanhSachDoiTacLayout.createSequentialGroup()
                .addGroup(jPanelDanhSachDoiTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDanhSachDoiTacLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelDanhSachDoiTacLayout.setVerticalGroup(
            jPanelDanhSachDoiTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDanhSachDoiTacLayout.createSequentialGroup()
                .addGroup(jPanelDanhSachDoiTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelDanhSachDoiTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelDanhSachDoiTac, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTablePartnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePartnerMouseClicked
        // TODO add your handling code here:
        int index = jTablePartner.getSelectedRow();
        this._partnerId = Integer.valueOf(jTablePartner.getValueAt(index, 0).toString());
        txtTenDoiTac.setText(jTablePartner.getValueAt(index, 2).toString());
        txtTenNDD.setText(jTablePartner.getValueAt(index, 6).toString());
        txtSoDienThoai.setText(jTablePartner.getValueAt(index, 5).toString());
        txtDiaChi.setText(jTablePartner.getValueAt(index, 4).toString());
        jTextAreaMoTa.setText(jTablePartner.getValueAt(index, 3).toString());
    }//GEN-LAST:event_jTablePartnerMouseClicked

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        //Xử lý thêm
        String tenDoiTac, tenNguoiDaiDien, sdt, diachi, mota;

        if(txtTenDoiTac.getText().equals("")) {
            StringHelpers.Message("Vui lòng nhập Tên Đói tác", "Thông báo", 2);
            txtTenDoiTac.requestFocus();
            return;
        } else if(txtTenNDD.getText().equals("")) {
            StringHelpers.Message("Vui lòng nhập Tên Người đại diện", "Thông báo", 2);
            txtTenNDD.requestFocus();
            return;
        } else if(txtSoDienThoai.getText().equals("")) {
            StringHelpers.Message("Vui lòng nhập Số điện thoại", "Thông báo", 2);
            txtSoDienThoai.requestFocus();
            return;
        } else if(txtDiaChi.getText().equals("")) {
            StringHelpers.Message("Vui lòng nhập Địa chỉ", "Thông báo", 2);
            txtDiaChi.requestFocus();
            return;
        } else if(jTextAreaMoTa.getText().equals("")) {
            StringHelpers.Message("Vui lòng nhập Mô tả", "Thông báo", 2);
            jTextAreaMoTa.requestFocus();
            return;
        }

        tenDoiTac = txtTenDoiTac.getText();
        tenNguoiDaiDien = txtTenNDD.getText();
        sdt = txtSoDienThoai.getText();
        diachi = txtDiaChi.getText();
        mota = jTextAreaMoTa.getText();

        Partner dto = new Partner();
        dto.setPartnerId(this._partnerId);
        dto.setPartnerName(tenDoiTac);
        dto.setDescription(mota);
        dto.setNumPhone(sdt);
        dto.setAddress(diachi);
        dto.setRepresentFullname(tenNguoiDaiDien);

        if( partnerService.insert(dto) ) {
            StringHelpers.Message("Đối tác đã được thêm vào csdl", "Thành công", 1);
        } else {
            StringHelpers.Message("Vui lòng thử lại", "Thất bại", 2);
        }
        getDataPartner();
        resetTablePartner();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        Serializable tenDoiTac, tenNguoiDaiDien, sdt, diachi, mota;

        if(txtTenDoiTac.getText().equals("")) {
            StringHelpers.Message("Vui lòng nhập Tên Đói tác", "Thông báo", 2);
            txtTenDoiTac.requestFocus();
            return;
        } else if(txtTenNDD.getText().equals("")) {
            StringHelpers.Message("Vui lòng nhập Tên Người đại diện", "Thông báo", 2);
            txtTenNDD.requestFocus();
            return;
        } else if(txtSoDienThoai.getText().equals("")) {
            StringHelpers.Message("Vui lòng nhập Số điện thoại", "Thông báo", 2);
            txtSoDienThoai.requestFocus();
            return;
        } else if(txtDiaChi.getText().equals("")) {
            StringHelpers.Message("Vui lòng nhập Địa chỉ", "Thông báo", 2);
            txtDiaChi.requestFocus();
            return;
        }
        //

        tenDoiTac = txtTenDoiTac.getText();
        tenNguoiDaiDien = txtTenNDD.getText();
        sdt = txtSoDienThoai.getText();
        diachi = txtDiaChi.getText();
        mota = jTextAreaMoTa.getText();

        Partner dto = new Partner();
        dto.setPartnerId(this._partnerId);
        dto.setPartnerName(tenDoiTac);
        dto.setDescription(mota);
        dto.setNumPhone(sdt);
        dto.setAddress(diachi);
        dto.setRepresentFullname(tenNguoiDaiDien);

        if( partnerService.update(dto) ) {
            StringHelpers.Message("Đối tác đã được cập nhật", "Thành công", 1);
        } else {
            StringHelpers.Message("Vui lòng thử lại", "Thất bại", 2);
        }
        getDataPartner();
        resetTablePartner();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog (null, "Bạn chắc chắn muốn xóa đối tác này?", "Warning", JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            Partner dto = new Partner();
            dto.setPartnerId(this._partnerId);
            if( partnerService.delete(dto) ) {
                StringHelpers.Message("Đối tác đã được Xóa thành công", "Thành công", 1);
            } else {
                StringHelpers.Message("Vui lòng thử lại", "Thất bại", 2);
            }
            getDataPartner();
            resetTablePartner();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        resetTablePartner();
    }//GEN-LAST:event_btnResetActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        getDataPartner();
        jTablePartner.getColumnModel().getColumn(0).setMinWidth(0);
        jTablePartner.getColumnModel().getColumn(0).setMaxWidth(0);
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelDanhSachDoiTac;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablePartner;
    private javax.swing.JTextArea jTextAreaMoTa;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenDoiTac;
    private javax.swing.JTextField txtTenNDD;
    // End of variables declaration//GEN-END:variables
}
