/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components.interfaces;

import components.entity.Partner;
import components.services.PartnerService;
import components.utils.StringHelpers;
import java.io.Serializable;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import javax.swing.JFileChooser;
import java.io.FileInputStream;
import java.io.File;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Cell;
import java.io.FileNotFoundException;
import java.io.IOException;

/**
 *
 * @author LuuDV
 */
public class frmPartner extends javax.swing.JPanel {
    private int _partnerId = -1;
    int pageSize = 10;
    long count;
    int totalPage, residual, page = 1;
    int start = 0;
    int end;
    DefaultTableModel tableModel;
    PartnerService partnerService;
    List<Partner> listAll;
    /**
     * Creates new form frmPartner
     */
    public frmPartner() {
        initComponents();
        partnerService = new PartnerService();
        onLoad();
    }
    private void onLoad() {
        count = partnerService.countTable();
        totalPage = (int)(Math.ceil((float)count/pageSize));
        listAll = partnerService.getDataPartner();
    }
    
    //--Code Đồi tác---------------------------------------------------=-/
    private void getHeaderTable() {
        Object[] obj = new Object[]{"ID", "STT", "Tên đối tác", "Mô tả", "Địa chỉ", "Số điện thoại", "Tên người đại diện"};
        tableModel = new DefaultTableModel(obj, 0);
        jTablePartner.setModel(tableModel);
    }
    private void getDataPartner() {
        int c = 0;
        try {
            start = (page-1)*pageSize;
            end = pageSize*page;
            if(end > listAll.size()){
                end = listAll.size();
            }
            List<Partner> listProduct = partnerService.getListByPagination(listAll, start, end);
             Iterator iter = listProduct.iterator();
            while (iter.hasNext()) {
                Partner partner = (Partner) iter.next();
                Object[] item = new Object[7];
                    item[0] = partner.getPartnerId();
                    item[1] = ++c + start;
                    item[2] = partner.getPartnerName();
                    item[3] = partner.getDescription();
                    item[4] = partner.getAddress();
                    item[5] = partner.getNumPhone();
                    item[6] = partner.getRepresentFullname();
                    tableModel.addRow(item);
            }
            jTablePartner.getColumnModel().getColumn(0).setMinWidth(0);
            jTablePartner.getColumnModel().getColumn(0).setMaxWidth(0);
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
        lblpaging.setText(page + "/" + totalPage);
        lblPage.setText("" + page);
    }
    
    private void resetTablePartner()
    {
        txtTenDoiTac.setText("");
        txtTenNDD.setText("");
        txtSoDienThoai.setText("");
        txtDiaChi.setText("");
        jTextAreaMoTa.setText("");
        
    }
    //---------------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDanhSachDoiTac = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePartner = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTenDoiTac = new javax.swing.JTextField();
        txtTenNDD = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtDiaChi = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaMoTa = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSearchField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbTen = new javax.swing.JCheckBox();
        cbMota = new javax.swing.JCheckBox();
        cbDiaChi = new javax.swing.JCheckBox();
        cbPhone = new javax.swing.JCheckBox();
        cbNDD = new javax.swing.JCheckBox();
        btnFilter = new javax.swing.JButton();
        btnPreAll = new javax.swing.JButton();
        btnPre = new javax.swing.JButton();
        lblPage = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnNextAll = new javax.swing.JButton();
        lblpaging = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jTablePartner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "STT", "Tên đối tác", "Mô tả", "Địa chỉ", "Số điện thoại", "Tên người đại diện"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTablePartner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePartnerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePartner);

        jLabel8.setText("Tên đối tác:");

        jLabel9.setText("Tên Người đại diện:");

        jLabel10.setText("Số điện thoại:");

        jLabel11.setText("Địa chỉ:");

        jLabel12.setText("Mô tả:");

        btnInsert.setText("Thêm");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setText("Chỉnh sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jButton1.setText("Import Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnInsert)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(18, 18, 18)
                .addComponent(btnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTextAreaMoTa.setColumns(20);
        jTextAreaMoTa.setRows(5);
        jScrollPane3.setViewportView(jTextAreaMoTa);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenDoiTac)
                    .addComponent(txtTenNDD, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTenDoiTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTenNDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel12)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Tìm kiếm");

        jLabel1.setText("Từ khòa:");

        jLabel2.setText("Lọc theo:");

        cbTen.setText("Tên");

        cbMota.setText("Mô tả");

        cbDiaChi.setText("Địa chỉ");

        cbPhone.setText("Số điện thoại");

        cbNDD.setText("Tên người đại diện");

        btnFilter.setText("Filter");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel14))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbDiaChi)
                                    .addComponent(cbTen))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMota)
                                    .addComponent(cbPhone)))
                            .addComponent(cbNDD))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbTen)
                            .addComponent(cbMota))
                        .addGap(9, 9, 9)
                        .addComponent(cbDiaChi))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(cbPhone)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbNDD)
                .addGap(18, 18, 18)
                .addComponent(btnFilter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPreAll.setText("<<");
        btnPreAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreAllActionPerformed(evt);
            }
        });

        btnPre.setText("<");
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });

        lblPage.setText("1");

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnNextAll.setText(">>");
        btnNextAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextAllActionPerformed(evt);
            }
        });

        lblpaging.setText("0/1");

        javax.swing.GroupLayout jPanelDanhSachDoiTacLayout = new javax.swing.GroupLayout(jPanelDanhSachDoiTac);
        jPanelDanhSachDoiTac.setLayout(jPanelDanhSachDoiTacLayout);
        jPanelDanhSachDoiTacLayout.setHorizontalGroup(
            jPanelDanhSachDoiTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDanhSachDoiTacLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane2)
            .addGroup(jPanelDanhSachDoiTacLayout.createSequentialGroup()
                .addGap(384, 384, 384)
                .addComponent(btnPreAll)
                .addGap(18, 18, 18)
                .addComponent(btnPre)
                .addGap(18, 18, 18)
                .addComponent(lblPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNextAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblpaging)
                .addContainerGap(378, Short.MAX_VALUE))
        );
        jPanelDanhSachDoiTacLayout.setVerticalGroup(
            jPanelDanhSachDoiTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDanhSachDoiTacLayout.createSequentialGroup()
                .addGroup(jPanelDanhSachDoiTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanelDanhSachDoiTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPreAll)
                    .addComponent(btnPre)
                    .addComponent(lblPage)
                    .addComponent(btnNext)
                    .addComponent(btnNextAll)
                    .addComponent(lblpaging))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1006, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelDanhSachDoiTac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelDanhSachDoiTac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTablePartnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePartnerMouseClicked
        // TODO add your handling code here:
        int index = jTablePartner.getSelectedRow();
        this._partnerId = Integer.valueOf(jTablePartner.getValueAt(index, 0).toString());
        txtTenDoiTac.setText(jTablePartner.getValueAt(index, 2).toString());
        txtTenNDD.setText(jTablePartner.getValueAt(index, 6).toString());
        txtSoDienThoai.setText(jTablePartner.getValueAt(index, 5).toString());
        txtDiaChi.setText(jTablePartner.getValueAt(index, 4).toString());
        jTextAreaMoTa.setText(jTablePartner.getValueAt(index, 3).toString());
    }//GEN-LAST:event_jTablePartnerMouseClicked

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        //Xử lý thêm
        String tenDoiTac, tenNguoiDaiDien, sdt, diachi, mota;

        if(txtTenDoiTac.getText().equals("")) {
            StringHelpers.Message("Vui lòng nhập Tên Đói tác", "Thông báo", 2);
            txtTenDoiTac.requestFocus();
            return;
        } else if(txtTenNDD.getText().equals("")) {
            StringHelpers.Message("Vui lòng nhập Tên Người đại diện", "Thông báo", 2);
            txtTenNDD.requestFocus();
            return;
        } else if(txtSoDienThoai.getText().equals("")) {
            StringHelpers.Message("Vui lòng nhập Số điện thoại", "Thông báo", 2);
            txtSoDienThoai.requestFocus();
            return;
        } else if(txtDiaChi.getText().equals("")) {
            StringHelpers.Message("Vui lòng nhập Địa chỉ", "Thông báo", 2);
            txtDiaChi.requestFocus();
            return;
        } else if(jTextAreaMoTa.getText().equals("")) {
            StringHelpers.Message("Vui lòng nhập Mô tả", "Thông báo", 2);
            jTextAreaMoTa.requestFocus();
            return;
        }

        tenDoiTac = txtTenDoiTac.getText();
        tenNguoiDaiDien = txtTenNDD.getText();
        sdt = txtSoDienThoai.getText();
        diachi = txtDiaChi.getText();
        mota = jTextAreaMoTa.getText();

        Partner dto = new Partner();
        dto.setPartnerId(this._partnerId);
        dto.setPartnerName(tenDoiTac);
        dto.setDescription(mota);
        dto.setNumPhone(sdt);
        dto.setAddress(diachi);
        dto.setRepresentFullname(tenNguoiDaiDien);

        if( partnerService.insert(dto) ) {
            StringHelpers.Message("Đối tác đã được thêm vào csdl", "Thành công", 1);
        } else {
            StringHelpers.Message("Vui lòng thử lại", "Thất bại", 2);
        }
        onLoad();
        getHeaderTable();
        getDataPartner();
        resetTablePartner();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String tenDoiTac, tenNguoiDaiDien, sdt, diachi, mota;

        if(txtTenDoiTac.getText().equals("")) {
            StringHelpers.Message("Vui lòng nhập Tên Đói tác", "Thông báo", 2);
            txtTenDoiTac.requestFocus();
            return;
        } else if(txtTenNDD.getText().equals("")) {
            StringHelpers.Message("Vui lòng nhập Tên Người đại diện", "Thông báo", 2);
            txtTenNDD.requestFocus();
            return;
        } else if(txtSoDienThoai.getText().equals("")) {
            StringHelpers.Message("Vui lòng nhập Số điện thoại", "Thông báo", 2);
            txtSoDienThoai.requestFocus();
            return;
        } else if(txtDiaChi.getText().equals("")) {
            StringHelpers.Message("Vui lòng nhập Địa chỉ", "Thông báo", 2);
            txtDiaChi.requestFocus();
            return;
        }
        //

        tenDoiTac = txtTenDoiTac.getText();
        tenNguoiDaiDien = txtTenNDD.getText();
        sdt = txtSoDienThoai.getText();
        diachi = txtDiaChi.getText();
        mota = jTextAreaMoTa.getText();

        Partner dto = new Partner();
        dto.setPartnerId(this._partnerId);
        dto.setPartnerName(tenDoiTac);
        dto.setDescription(mota);
        dto.setNumPhone(sdt);
        dto.setAddress(diachi);
        dto.setRepresentFullname(tenNguoiDaiDien);

        if( partnerService.update(dto) ) {
            StringHelpers.Message("Đối tác đã được cập nhật", "Thành công", 1);
        } else {
            StringHelpers.Message("Vui lòng thử lại", "Thất bại", 2);
        }
        onLoad();
        getHeaderTable();
        getDataPartner();
        resetTablePartner();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog (null, "Bạn chắc chắn muốn xóa đối tác này?", "Warning", JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            Partner dto = new Partner();
            dto.setPartnerId(this._partnerId);
            if( partnerService.delete(dto) ) {
                StringHelpers.Message("Đối tác đã được Xóa thành công", "Thành công", 1);
            } else {
                StringHelpers.Message("Vui lòng thử lại", "Thất bại", 2);
            }
            onLoad();
            getHeaderTable();
            getDataPartner();
            resetTablePartner();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        onLoad();
        resetTablePartner();
        getHeaderTable();
        getDataPartner();
    }//GEN-LAST:event_btnResetActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        getHeaderTable();
        getDataPartner();
    }//GEN-LAST:event_formComponentShown

    private void btnPreAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreAllActionPerformed
        // TODO add your handling code here:
        if (page > 1) {
            page = 1;
            getHeaderTable();
            getDataPartner();
        }
    }//GEN-LAST:event_btnPreAllActionPerformed

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
        // TODO add your handling code here:
         if (page > 1) {
            page--;
            getHeaderTable();
            getDataPartner();
        }
    }//GEN-LAST:event_btnPreActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
         if (page < totalPage) {
            page++;
            getHeaderTable();
            getDataPartner();
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnNextAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextAllActionPerformed
        // TODO add your handling code here:
        if (page < totalPage) {
            page = totalPage;
            getHeaderTable();
            getDataPartner();
        }
    }//GEN-LAST:event_btnNextAllActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        // TODO add your handling code here:
        Boolean isName = false,
                isDescription = false,
                isAddress = false,
                isPhone = false,
                isNDD = false;
        if (cbTen.isSelected()) {
            isName = true;
        }
        if (cbMota.isSelected()) {
            isDescription = true;
        }
        if (cbDiaChi.isSelected()) {
            isAddress = true;
        }
        if (cbPhone.isSelected()) {
            isPhone = true;
        }
        if (cbNDD.isSelected()) {
            isNDD = true;
        }
        
        String filter = txtSearchField.getText();
        if (filter.equals("") == true) {
            StringHelpers.Message("Vui lòng nhập từ khóa", "Thông báo", 2);
            return;
        }
        
        count = partnerService.countTableFilter(filter, isName, isDescription, isAddress, isPhone, isNDD);
        totalPage = (int)(Math.ceil((float)count/pageSize));
        getHeaderTable();
        
        int c = 0;
        try {
            List<Partner> lists = partnerService.getDataPartnerFilter(filter, isName, isDescription, isAddress, isPhone, isNDD);
            start = (page-1)*pageSize;
            end = pageSize*page;
            if(end > lists.size()){
                end = lists.size();
            }
            List<Partner> listProduct = partnerService.getListByPagination(lists, start, end);
            Iterator iter = listProduct.iterator();
            while (iter.hasNext()) {
                Partner partner = (Partner) iter.next();
                Object[] item = new Object[7];
                    item[0] = partner.getPartnerId();
                    item[1] = ++c + start;
                    item[2] = partner.getPartnerName();
                    item[3] = partner.getDescription();
                    item[4] = partner.getAddress();
                    item[5] = partner.getNumPhone();
                    item[6] = partner.getRepresentFullname();
                    tableModel.addRow(item);
            }
            jTablePartner.getColumnModel().getColumn(0).setMinWidth(0);
            jTablePartner.getColumnModel().getColumn(0).setMaxWidth(0);
        } catch (Exception ex) {
            System.out.println("123");
            System.out.println(ex.toString());
        }
        lblpaging.setText(page + "/" + totalPage);
        lblPage.setText("" + page);
    }//GEN-LAST:event_btnFilterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String filename, dir;
        JFileChooser c = new JFileChooser();
        int rVal = c.showOpenDialog(frmPartner.this);
        if (rVal == JFileChooser.APPROVE_OPTION) {
            filename = c.getSelectedFile().getName();
            dir = c.getCurrentDirectory().toString();
            try {
                FileInputStream excelFile = new FileInputStream(new File(dir + "/" + filename));
                Workbook workbook = new XSSFWorkbook(excelFile);
                Sheet datatypeSheet = workbook.getSheetAt(0);
                DataFormatter fmt = new DataFormatter();
                Iterator<Row> iterator = datatypeSheet.iterator();
                Row firstRow = iterator.next(); // title row, no insert

                int i=0;
                while (iterator.hasNext()) {
                    Row currentRow = iterator.next();
                    Partner partner = new Partner();
                    partner.setPartnerName(fmt.formatCellValue(currentRow.getCell(0)));
                    partner.setDescription(fmt.formatCellValue(currentRow.getCell(1)));
                    partner.setAddress(fmt.formatCellValue(currentRow.getCell(2)));
                    partner.setNumPhone(fmt.formatCellValue(currentRow.getCell(3)));
                    partner.setRepresentFullname(fmt.formatCellValue(currentRow.getCell(4)));

                    partnerService.insert(partner);
                    i++;
                }
                workbook.close();
                StringHelpers.Message("IMPORT DỮ LIỆU THÀNH CÔNG!\n\n File import: " + filename + " .\n Số dòng import thành công: " + i + " dòng", "Thành công", 1);
                onLoad();

                getHeaderTable();
                getDataPartner();
            } catch (FileNotFoundException e) {
                e.printStackTrace();
                StringHelpers.Message("Import dữ liệu không thành công", "Không thành công", 2);
            } catch (IOException e) {
                e.printStackTrace();
                StringHelpers.Message("Import dữ liệu không thành công", "Không thành công", 2);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNextAll;
    private javax.swing.JButton btnPre;
    private javax.swing.JButton btnPreAll;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox cbDiaChi;
    private javax.swing.JCheckBox cbMota;
    private javax.swing.JCheckBox cbNDD;
    private javax.swing.JCheckBox cbPhone;
    private javax.swing.JCheckBox cbTen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelDanhSachDoiTac;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablePartner;
    private javax.swing.JTextArea jTextAreaMoTa;
    private javax.swing.JLabel lblPage;
    private javax.swing.JLabel lblpaging;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtSearchField;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenDoiTac;
    private javax.swing.JTextField txtTenNDD;
    // End of variables declaration//GEN-END:variables
}
